# Generated by Django 5.2.8 on 2026-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_statusmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('added_by', models.CharField(max_length=19)),
            ],
        ),
    ]
